[package]
name = "optioncontracts"
version = "0.0.0"
authors = ["David Holtz <david.richard.holtz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
